"""empty message

Revision ID: 55ba6c372296
Revises: 7b93da0fec07
Create Date: 2022-11-20 13:10:16.862596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ba6c372296'
down_revision = '7b93da0fec07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('rut',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('rut',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=False)

    # ### end Alembic commands ###
